### ISSUE TITLE
Load previous thumbnails

### ISSUE THREAD

**Issue by pedrofsn** [asantibanez/Patio#11]
This library it's perfect to work with registers. But it will better if works with editing registers too. For this will be necessary load previous thumbnails, can it be done? 

Suggestion, use imageloader to load from URL.

**Comment by asantibanez** [comment]
Hi @pedrofsn! Thanks for using Patio. I haven´t given it too much time to develop and address issues but I would like to start by helping you. Can you please elaborate on the "registers"? An example or flow of events could be helpful.

**Comment by pedrofsn** [comment]
Sorry for my english.

Basically, it's a feature for change selected image. 
But I suppose that it isn't the library purpose.

**Comment by wviana** [comment]
@pedrofsn What do you mean by change ? Edit the photo/picture ?

**Comment by pedrofsn** [comment]
@wviana today you have to select image and if you don't like image you can delete this image and select other. 

When I wrote this suggestion was the library provide fixed number of "photo-square-selectors". And the possibiliy to change an previous selected photo instead of exclude and select a new photo by a "new photo-square-selector".

But now I can see, this isn't the purpose of library. I'm sorry for my confusion.

**Comment by wviana** [comment]
@pedrofsn 
Now I got it.
With this you would be able to keep the photos order and change a specific one, instead of removing.

for example, 
I have photo
A | B | C

Today if I want to change B to D I would have to select B, delete than add D, going to 
A | C | D

Your change suggestion would permit to use

A | D | C

Is that it ?

**Comment by pedrofsn** [comment]
Exactly!

**Comment by wviana** [comment]
It would have to have a third actions to change it. Really probably  out of scope of the project.
You may extend this project to your specific needs.

**Comment by pedrofsn** [comment]
I agree with you.

**Comment by asantibanez** [comment]
Hi @wviana @pedrofsn 

I understand you want the library to be like a placeholder for a set of images. As of now, that feature is not part of the library's core. Like @wviana said, feel free to fork the project or include a PR with the intended feature.
