### ISSUE TITLE
Can you upload this library to maven central repository?

### ISSUE THREAD

**Issue by y2kshane** [asantibanez/Patio#2]
Can you upload this to maven central repository? it would be easy for developers to add this library into their projects.
thanks.

**Comment by danielgomezrico** [comment]
+1

**Comment by wviana** [comment]
Hey, there are a pull request from JitPack team to add this library to the repository.
I did pull this to my fork, although I implemented pt-BR translations, and a Spacing hiding when no pictures taken.

If you wanna check it while @asantibanez  don't answer, just check mine or Jitpack fork.

mine on: https://github.com/wviana/Patio
Jitpack on: https://github.com/jitpack-io/Patio

**Comment by asantibanez** [comment]
Done. Thanks @wviana for your contribution as well as @jitpack-io for making it available through gradle.
