### ISSUE TITLE
JitPack not working.

### ISSUE THREAD

**Issue by wviana** [asantibanez/Patio#4]
Patio not supporting JitPack,

more information.

http://stackoverflow.com/questions/29800449/how-to-import-patio-library-in-my-project

Maybe something about it could be done:

https://github.com/jitpack/jitpack.io/blob/master/BUILDING.md

**Comment by jitpack-io** [comment]
Should get fixed with PR #5

**Comment by asantibanez** [comment]
Merged @jitpack-io PR for Jitpack integration
