### ISSUE TITLE
Hide photo space when no photo add yet

### ISSUE THREAD

**Issue by wviana** [asantibanez/Patio#6]
When no photo is loaded yet, it could not show the white space between top buttons and the loaded photos counter
![captura de tela 2015-04-23 as 15 39 06](https://cloud.githubusercontent.com/assets/1062631/7304602/e97f1074-e9ce-11e4-884a-844e3fad64ba.png)

**Comment by wviana** [comment]
I did fix it in my Fork,

**Comment by asantibanez** [comment]
Merged your suggestions. Thumbnails show/hide automatically when available.
